version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - traefik-public-certificates:/etc/traefik/acme
    networks:
      - barber-network
    environment:
      - DOMAIN=${DOMAIN:-top-code.dev.br}
      - ACME_EMAIL=${ACME_EMAIL:-frandevjobs@gmail.com}
    env_file:
      - .env.prod

  app:
    build:
      context: .
      target: production-stage
    container_name: barber-web-prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.app-http.entrypoints=web"
      - "traefik.http.routers.app-https.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.app-https.entrypoints=websecure"
      - "traefik.http.routers.app-https.tls=true"
      - "traefik.http.routers.app-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=80"
    environment:
      - DOMAIN=${DOMAIN:-top-code.dev.br}
      - ACME_EMAIL=${ACME_EMAIL:-frandevjobs@gmail.com}
      - VITE_APP_API_URL=${VITE_APP_API_URL:-https://api.seudominio.com}
    env_file:
      - .env.prod
    networks:
      - barber-network
    restart: unless-stopped

networks:
  barber-network:
    driver: bridge

volumes:
  traefik-public-certificates:
