version: '3.8'

services:
  app:
    build:
      context: .
      target: build-stage
    container_name: barber-web-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - VITE_APP_API_URL=${VITE_APP_API_URL:-http://localhost:3001}
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    networks:
      - barber-network

networks:
  barber-network:
    driver: bridge
